### ISSUE TITLE
Push back 1" while placing hatch

### ISSUE THREAD

**Issue by jhajel** [GwhsRobotics3/SwerveDriveSpark#4]
If placing the drive motors in coast mode does not help, we can add a push back when placing a hatch on the cargo ship.  Note that we do not want to do this on the rocket, so we'll need to be careful.

**Comment by GwhsRobotics3** [comment]
Added a push back command mapped to a button

**Comment by jhajel** [comment]
We may want to make it automatic when we are placing the hatch on the cargo ship.  We probably don't want it for rocket ship.  Also, we may want to try coast mode first.
